import { app, BrowserWindow, dialog, ipcMain, shell } from "electron";
import { autoUpdater } from "electron-updater";
import { join } from "node:path";
import * as service from "./services.js";
import { logError } from "./logging.js";
let window:BrowserWindow|undefined;
const root=(value:unknown)=>{if(typeof value!=="string"||!value.trim())throw new Error("A project path is required.");return value;};
function handle(channel:string, fn:(...args:any[])=>unknown){ipcMain.handle(channel,async(_event,...args)=>{try{return await fn(...args);}catch(error){await logError(channel,error).catch(()=>undefined);throw error;}});}
async function boot(){window=new BrowserWindow({width:1400,height:900,minWidth:1000,minHeight:650,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,preload:join(import.meta.dirname,"preload.js")}});const url=process.env.VITE_DEV_SERVER_URL;if(url)await window.loadURL(url);else await window.loadFile(join(app.getAppPath(),"dist","index.html"));}
app.whenReady().then(async()=>{handle("projects:list",service.registry);handle("projects:create",(p,t,l)=>service.create(root(p),String(t),l==="he"?"he":"en"));handle("projects:open",p=>service.remember(root(p)));handle("projects:remove",service.remove);handle("projects:delete",service.deleteLocal);handle("projects:clone",(url,dest)=>service.clone(String(url),root(dest)));handle("projects:importLegacy",service.importLegacyRegistry);handle("editor:pages",p=>service.pages(root(p)));handle("editor:savePage",(p,page)=>service.savePage(root(p),page));handle("editor:deletePage",(p,file)=>service.deletePage(root(p),String(file)));handle("editor:settings",p=>service.settings(root(p)));handle("editor:saveSettings",(p,s)=>service.saveSettings(root(p),s));handle("editor:validate",p=>service.validateProject(root(p)));handle("editor:build",p=>service.buildProject(root(p)));handle("editor:migrate",p=>service.migrateProject(root(p)));handle("editor:themes",service.themes);handle("editor:selectTheme",(p,id)=>service.selectTheme(root(p),String(id)));handle("editor:media",p=>service.media(root(p)));handle("editor:importImage",p=>service.importImage(root(p)));handle("editor:deleteImage",(p,file)=>service.deleteImage(root(p),String(file)));handle("editor:favicon",p=>service.chooseFavicon(root(p)));handle("editor:preview",p=>service.preview(root(p)));handle("git:status",p=>service.git(root(p),["status","--short","--branch"]));handle("git:init",p=>service.git(root(p),["init"]));handle("git:sync",async p=>{await service.git(root(p),["fetch","origin"]);return service.git(root(p),["pull","--ff-only"]);});handle("git:commit",(p,msg)=>service.git(root(p),["add","-A"]).then(()=>service.git(root(p),["commit","-m",String(msg)])));handle("git:push",p=>service.git(root(p),["push"]));handle("git:history",p=>service.git(root(p),["log","--oneline","-30"]));handle("git:identity",(p,n,e)=>Promise.all([service.git(root(p),["config","user.name",String(n)]),service.git(root(p),["config","user.email",String(e)])]));handle("app:version",()=>app.getVersion());handle("app:update",async()=>{if(!app.isPackaged)return {state:"development"};return autoUpdater.checkForUpdates();});handle("app:installUpdate",()=>autoUpdater.quitAndInstall());handle("app:chooseDirectory",async()=>{const r=await dialog.showOpenDialog({properties:["openDirectory","createDirectory"]});return r.canceled?undefined:r.filePaths[0];});handle("app:openExternal",(url)=>shell.openExternal(String(url)));await boot();});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit();});
